server:
  port: 8888
spring:
  data:
    mongodb:
      host: localhost
      database: canoo-book-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
